runtime: python27
api_version: 1
default_expiration: "1s"
threadsafe: false
 
handlers:
- url: /static/
  static_dir: static
- url: /
  script: main.app
  secure: always
- url: /api/.*
  script: api.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest